name       : avrdude
version    : 6.3
release    : 4
source     :
    - http://download.savannah.gnu.org/releases/avrdude/avrdude-6.3.tar.gz : 0f9f731b6394ca7795b88359689a7fa1fba818c6e1d962513eb28da670e0a196
license    : GPL-2.0-or-later
component  : programming.tools
summary    : AVR Downloader Uploader
description: |
    AVRDUDE is a utility to download/upload/manipulate the ROM and EEPROM contents of AVR microcontrollers using the in-system programming technique (ISP).
builddeps  :
    - pkgconfig(libusb)
    - pkgconfig(libftdi1)
    - elfutils-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Make-avrdude-stateless.patch
    %configure --enable-dependency-tracking \
               --enable-static=no \
               --enable-linuxgpio
build      : |
    %make
install    : |
    %make_install
    # Move files to stateless path
    install -dm00644 $installdir/usr/share/defaults/avrdude
    install -Dm00755 $workdir/avrdude.conf $installdir/usr/share/defaults/avrdude/avrdude.conf
    rm -rf $installdir/etc
