name       : avrdude
version    : 6.3
release    : 3
source     :
    - http://download.savannah.gnu.org/releases/avrdude/avrdude-6.3.tar.gz : 0f9f731b6394ca7795b88359689a7fa1fba818c6e1d962513eb28da670e0a196
license    : GPL-2.0
component  : programming.tools
summary    : AVR Downloader Uploader
builddeps  :
    - pkgconfig(libusb)
    - pkgconfig(libftdi1)
    - elfutils-devel
description: |
    AVRDUDE is a utility to download/upload/manipulate the ROM and EEPROM contents of AVR microcontrollers using the in-system programming technique (ISP).
setup      : |
    %configure --enable-dependency-tracking \
               --enable-static=no \
               --enable-linuxgpio
build      : |
    %make
install    : |
    %make_install
