name       : avrdude
version    : 7.1
release    : 7
source     :
    - git|https://github.com/avrdudes/avrdude.git: v7.1
license    : GPL-2.0-or-later
component  : programming.tools
summary    : AVR Downloader Uploader
description: |
    AVRDUDE is a utility to download/upload/manipulate the ROM and EEPROM contents of AVR microcontrollers using the in-system programming technique (ISP).
builddeps  :
    - pkgconfig(libelf)
    - pkgconfig(libftdi1)
    - pkgconfig(libusb)
    - pkgconfig(libusb-1.0)
    - pkgconfig(hidapi-libusb)
    - pkgconfig(readline)
setup      : |
    %patch -p1 < $pkgfiles/0001-Make-avrdude-stateless.patch
    %cmake_ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo\
                 -D BUILD_SHARED_LIBS=1 \
                 -D HAVE_LINUXGPIO=1\
                 -D HAVE_LINUXSPI=1
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Move files to stateless path
    install -dm00644 $installdir/usr/share/defaults/avrdude
    mv $installdir/usr/etc/avrdude.conf $installdir/usr/share/defaults/avrdude/avrdude.conf
    rm -rf $installdir/usr/etc